### ISSUE TITLE
Allowed PHP Nightly to be failure

### ISSUE THREAD

**Issue by peter279k** [php-api-clients/resource-test-utilities#32]
As title, we need to set the `php-nightly` to allow to be failure during Travis CI build.

We cannot guarantee that the unstable PHP version always pass the tests on CI build every time.

**Comment by WyriHaximus** [comment]
Sounds good to me :+1: , want to make the PR for that?

**Comment by peter279k** [comment]
Hi @WyriHaximus, thank you for your reply and concern.

I will create related PR about this issue.

**Comment by WyriHaximus** [comment]
Closed via #33
